config/routes.rb
TrainsDevelopment::Application.routes.draw do
  resources :stations
  root :to => 'stations#index'

end

app/models/station.rb
class Station < ActiveRecord::Base
  attr_accessible :name

  validates :name, :presence => true

  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController

  def index
    @stations = Station.all
    respond_to do |format|
      format.html
      format.json { render :json => @stations }
    end
  end

  def new
    @station = Station.new
  end

  def edit
    @station = Station.find(params[:id])
  end

  def create
    @station = Station.new(params[:station])

    if @station.save
      redirect_to stations_path, :notice => 'Station was successfully created.'
    else
      render :action => "new"
    end
  end

  def update
    @station = Station.find(params[:id])

    if @station.update_attributes(params[:station])
      redirect_to stations_path, :notice => 'Station was successfully updated.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @station = Station.destroy(params[:id])
    redirect_to stations_path, :notice => 'Station was successfully deleted.'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/home/index.html.erb
<h1>Welcome to this beautiful application!</h1>

<p>Here's the list of stations:</p>

<ul>
  <% Station.all.each do |station| -%>
    <li><%= station %></li>
  <% end -%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrainsDevelopment</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container-fluid" style="margin-top: 40px">
    <div class="row-fluid">
      <div class="span2">
        <!--Sidebar content-->
        <ul class="well nav nav-list">
          <li class="nav-header">Trains app</li>
          <li><%= link_to "Welcome", root_path %></li>
          <li><%= link_to "Stations", stations_path %></li>
        </ul>
      </div>
      <div class="span10">
        <!--Body content-->
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/stations/_form.html.erb
<%= simple_form_for @station do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<%= render :partial => 'form' %>

app/views/stations/index.html.erb
<h1>Stations</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @stations.each do |station| -%>
      <tr>
        <td><%= station.name %></td>
        <td><%= station.address %></td>
        <td>
          <%= link_to "Edit", edit_station_path(station), :class => "btn btn-info" %>
          <%= link_to "Delete", station, :method => :delete, :class => "btn btn-danger" %>
        </td>
      </tr>
    </tr>
    <% end -%>
  </tbody>
</table>

<%= link_to "Add a new station", new_station_path, :class => "btn btn-info" %>

app/views/stations/new.html.erb
<%= render :partial => 'form' %>